-- ============================================================
-- صاحبك (Sahibak) — Database Schema
-- ============================================================
-- This file contains:
-- - All table definitions
-- - All indexes
-- - All RLS policies
-- - Views
-- ============================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- TABLES
-- ============================================================

-- ========================================
-- PROFILES TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  phone TEXT,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'provider', 'admin')),
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  warning_count INT NOT NULL DEFAULT 0,
  ban_reason TEXT,
  banned_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS profiles_role_idx ON profiles(role);
CREATE INDEX IF NOT EXISTS profiles_banned_idx ON profiles(is_banned);

-- ========================================
-- CATEGORIES TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  parent_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT,
  icon TEXT,
  color TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  show_on_home BOOLEAN DEFAULT TRUE,
  place_type_hint TEXT CHECK (place_type_hint IN ('shop', 'person', 'both')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS categories_parent_id_idx ON categories(parent_id);
CREATE INDEX IF NOT EXISTS categories_is_active_idx ON categories(is_active);
CREATE INDEX IF NOT EXISTS categories_show_on_home_idx ON categories(show_on_home);
CREATE INDEX IF NOT EXISTS categories_sort_order_idx ON categories(sort_order);

-- ========================================
-- PLACES TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS places (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  area TEXT NOT NULL DEFAULT 'المنصورية',
  place_type TEXT NOT NULL DEFAULT 'shop' CHECK (place_type IN ('shop', 'person')),
  name_ar TEXT NOT NULL,
  name_en TEXT,
  description_ar TEXT,
  description_en TEXT,
  phone TEXT NOT NULL,
  whatsapp TEXT,
  address_text TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  image_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_note TEXT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS places_provider_idx ON places(provider_id);
CREATE INDEX IF NOT EXISTS places_area_idx ON places(area);
CREATE INDEX IF NOT EXISTS places_status_idx ON places(status);
CREATE INDEX IF NOT EXISTS places_type_idx ON places(place_type);
CREATE INDEX IF NOT EXISTS places_deleted_at_idx ON places(deleted_at);
CREATE INDEX IF NOT EXISTS places_created_at_idx ON places(created_at DESC);
CREATE INDEX IF NOT EXISTS places_updated_idx ON places(updated_at);

-- ========================================
-- PLACE_CATEGORIES JUNCTION TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS place_categories (
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (place_id, category_id)
);

CREATE INDEX IF NOT EXISTS place_categories_category_id_idx ON place_categories(category_id);

-- ========================================
-- PLACE_SERVICES TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS place_services (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  name_ar TEXT NOT NULL,
  description_ar TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS place_services_place_id_idx ON place_services(place_id);
CREATE INDEX IF NOT EXISTS place_services_sort_order_idx ON place_services(sort_order);

-- ========================================
-- PLACE_IMAGES TABLE (V2 ready)
-- ========================================
CREATE TABLE IF NOT EXISTS place_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS place_images_place_idx ON place_images(place_id);

-- ========================================
-- PLACE_EDIT_REQUESTS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS place_edit_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  provider_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS edit_req_place_idx ON place_edit_requests(place_id);
CREATE INDEX IF NOT EXISTS edit_req_provider_idx ON place_edit_requests(provider_id);
CREATE INDEX IF NOT EXISTS edit_req_status_idx ON place_edit_requests(status);

-- ========================================
-- OFFERS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  place_service_id UUID REFERENCES place_services(id) ON DELETE SET NULL,
  title_ar TEXT NOT NULL,
  description_ar TEXT,
  expires_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_note TEXT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS offers_place_id_idx ON offers(place_id);
CREATE INDEX IF NOT EXISTS offers_place_service_id_idx ON offers(place_service_id);
CREATE INDEX IF NOT EXISTS offers_status_idx ON offers(status);
CREATE INDEX IF NOT EXISTS offers_expires_at_idx ON offers(expires_at);
CREATE INDEX IF NOT EXISTS offers_deleted_at_idx ON offers(deleted_at);
CREATE INDEX IF NOT EXISTS offers_created_at_idx ON offers(created_at DESC);
CREATE INDEX IF NOT EXISTS offers_updated_idx ON offers(updated_at);

-- ========================================
-- NEWS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS news (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title_ar TEXT NOT NULL,
  body_ar TEXT,
  image_url TEXT,
  is_pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS news_is_pinned_idx ON news(is_pinned);
CREATE INDEX IF NOT EXISTS news_created_at_idx ON news(created_at DESC);

-- ========================================
-- FAVORITES TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS favorites (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, place_id)
);

CREATE INDEX IF NOT EXISTS favorites_user_id_idx ON favorites(user_id);
CREATE INDEX IF NOT EXISTS favorites_created_at_idx ON favorites(created_at DESC);

-- ========================================
-- LIKES TABLE (V2 ready)
-- ========================================
CREATE TABLE IF NOT EXISTS likes (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, place_id)
);

CREATE INDEX IF NOT EXISTS likes_place_idx ON likes(place_id);

-- ========================================
-- REPORTS TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS reports_place_id_idx ON reports(place_id);
CREATE INDEX IF NOT EXISTS reports_user_id_idx ON reports(user_id);
CREATE INDEX IF NOT EXISTS reports_status_idx ON reports(status);
CREATE INDEX IF NOT EXISTS reports_created_at_idx ON reports(created_at DESC);

-- ========================================
-- DEVICE_TOKENS TABLE (V2 ready)
-- ========================================
CREATE TABLE IF NOT EXISTS device_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT CHECK (platform IN ('android', 'ios', 'web')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, token)
);

-- ========================================
-- AUDIT_LOG TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id UUID NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS audit_log_admin_id_idx ON audit_log(admin_id);
CREATE INDEX IF NOT EXISTS audit_log_action_idx ON audit_log(action);
CREATE INDEX IF NOT EXISTS audit_log_target_type_idx ON audit_log(target_type);
CREATE INDEX IF NOT EXISTS audit_log_target_id_idx ON audit_log(target_id);
CREATE INDEX IF NOT EXISTS audit_log_created_at_idx ON audit_log(created_at DESC);

-- ========================================
-- APP_CONFIG TABLE
-- ========================================
CREATE TABLE IF NOT EXISTS app_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- VIEWS
-- ============================================================

CREATE OR REPLACE VIEW place_likes_count
  WITH (security_invoker = true) AS
SELECT place_id, COUNT(*) AS likes_count
FROM likes
GROUP BY place_id;

-- ============================================================
-- RLS (ROW LEVEL SECURITY)
-- ============================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE places ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_edit_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

-- ==================== PROFILES POLICIES ====================
CREATE POLICY "profiles_select_public" ON profiles
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "profiles_update_own" ON profiles
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = id);

-- ==================== CATEGORIES POLICIES ====================
CREATE POLICY "categories_select_public" ON categories
  FOR SELECT
  TO anon, authenticated
  USING (is_active = true);

-- ==================== NEWS POLICIES ====================
CREATE POLICY "news_select_public" ON news
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- ==================== PLACES POLICIES ====================
CREATE POLICY "places_select_public" ON places
  FOR SELECT
  TO anon, authenticated
  USING (
    status = 'approved'
    AND deleted_at IS NULL
    AND (provider_id IS NULL OR provider_id NOT IN (
      SELECT id FROM profiles WHERE is_banned = TRUE
    ))
  );

CREATE POLICY "places_select_provider_own" ON places
  FOR SELECT
  TO authenticated
  USING (auth.uid() = provider_id);

CREATE POLICY "places_insert_provider" ON places
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = provider_id);

CREATE POLICY "places_update_provider_own" ON places
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = provider_id);

-- ==================== PLACE_CATEGORIES POLICIES ====================
CREATE POLICY "place_categories_select_public" ON place_categories
  FOR SELECT
  TO anon, authenticated
  USING (
    place_id IN (
      SELECT id FROM places
      WHERE status = 'approved' AND deleted_at IS NULL
    )
  );

CREATE POLICY "place_categories_manage_provider_own" ON place_categories
  FOR ALL
  TO authenticated
  USING (
    place_id IN (
      SELECT id FROM places WHERE provider_id = auth.uid()
    )
  );

-- ==================== PLACE_SERVICES POLICIES ====================
CREATE POLICY "place_services_select_public" ON place_services
  FOR SELECT
  TO anon, authenticated
  USING (
    place_id IN (
      SELECT id FROM places
      WHERE status = 'approved' AND deleted_at IS NULL
    )
  );

CREATE POLICY "place_services_manage_provider_own" ON place_services
  FOR ALL
  TO authenticated
  USING (
    place_id IN (
      SELECT id FROM places WHERE provider_id = auth.uid()
    )
  );

-- ==================== PLACE_IMAGES POLICIES ====================
CREATE POLICY "place_images_select_public" ON place_images
  FOR SELECT
  TO anon, authenticated
  USING (
    place_id IN (
      SELECT id FROM places
      WHERE status = 'approved' AND deleted_at IS NULL
    )
  );

CREATE POLICY "place_images_manage_provider_own" ON place_images
  FOR ALL
  TO authenticated
  USING (
    place_id IN (
      SELECT id FROM places WHERE provider_id = auth.uid()
    )
  );

-- ==================== PLACE_EDIT_REQUESTS POLICIES ====================
CREATE POLICY "place_edit_requests_select_provider_own" ON place_edit_requests
  FOR SELECT
  TO authenticated
  USING (
    place_id IN (
      SELECT id FROM places WHERE provider_id = auth.uid()
    )
  );

CREATE POLICY "place_edit_requests_insert_provider" ON place_edit_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (
    place_id IN (
      SELECT id FROM places WHERE provider_id = auth.uid()
    )
  );

-- ==================== OFFERS POLICIES ====================
CREATE POLICY "offers_select_public" ON offers
  FOR SELECT
  TO anon, authenticated
  USING (status = 'approved' AND deleted_at IS NULL);

CREATE POLICY "offers_manage_provider_own" ON offers
  FOR ALL
  TO authenticated
  USING (
    place_id IN (
      SELECT id FROM places WHERE provider_id = auth.uid()
    )
  );

-- ==================== FAVORITES POLICIES ====================
CREATE POLICY "favorites_manage_own" ON favorites
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id);

-- ==================== LIKES POLICIES ====================
CREATE POLICY "likes_select_public" ON likes
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "likes_insert_own" ON likes
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "likes_delete_own" ON likes
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- ==================== REPORTS POLICIES ====================
CREATE POLICY "reports_insert_own" ON reports
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "reports_select_admin" ON reports
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- ==================== DEVICE_TOKENS POLICIES ====================
CREATE POLICY "device_tokens_manage_own" ON device_tokens
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id);

-- ==================== AUDIT_LOG POLICIES ====================
CREATE POLICY "audit_log_select_admin" ON audit_log
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "audit_log_insert_admin" ON audit_log
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- ==================== APP_CONFIG POLICIES ====================
CREATE POLICY "app_config_select_public" ON app_config
  FOR SELECT
  TO anon, authenticated
  USING (true);
