/*
  # Initial Schema — Sahibak Base Tables

  1. New Tables
    - `profiles` — user profiles with role (user/provider/admin), ban status
    - `categories` — hierarchical categories with parent_id self-reference
    - `places` — business/person listings with approval workflow
    - `place_categories` — junction table (place ↔ category)
    - `place_services` — services offered by a place
    - `place_images` — multiple images per place (V2)
    - `place_edit_requests` — provider edit requests needing admin approval
    - `offers` — time-limited offers on places/services
    - `news` — admin-posted news items
    - `favorites` — user favorite places
    - `likes` — user likes on places (V2)
    - `reports` — user reports on places
    - `device_tokens` — push notification tokens (V2)
    - `audit_log` — admin action audit trail
    - `app_config` — key-value configuration store

  2. Security
    - RLS enabled on all tables
    - Public read on approved, non-deleted places (excludes banned providers)
    - Provider INSERT/UPDATE on own places (status immutable for providers)
    - Admin-only UPDATE on places/offers status (approve/reject)
    - Admin-only INSERT/UPDATE/DELETE on categories and news
    - Admin-only UPDATE/DELETE on reports
    - Unique constraint on reports(user_id, place_id) prevents spam
    - Unique partial index on profiles.phone prevents duplicate accounts
    - pg_trgm GIN index on places.name_ar for efficient search

  3. Functions & Triggers
    - handle_new_user: auto-create profile on signup
    - touch_updated_at: auto-update updated_at on mutation
    - check_category_limit: enforce max categories per place type
    - check_provider_limits: enforce max places per provider from app_config

  4. Important Notes
    1) Providers CANNOT change the `status` field on their own places — only admins can approve/reject
    2) Same restriction applies to offers status
    3) Categories and news are fully admin-managed — no public write
    4) The reports unique constraint prevents a user from reporting the same place twice
*/

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ==================== TABLES ====================

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  phone TEXT,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'provider', 'admin')),
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  warning_count INT NOT NULL DEFAULT 0,
  ban_reason TEXT,
  banned_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS profiles_role_idx ON profiles(role);
CREATE INDEX IF NOT EXISTS profiles_banned_idx ON profiles(is_banned);
CREATE UNIQUE INDEX IF NOT EXISTS profiles_phone_unique ON profiles(phone) WHERE phone IS NOT NULL AND phone != '';

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  parent_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT,
  icon TEXT,
  color TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  show_on_home BOOLEAN DEFAULT TRUE,
  place_type_hint TEXT CHECK (place_type_hint IN ('shop', 'person', 'both')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS categories_parent_id_idx ON categories(parent_id);
CREATE INDEX IF NOT EXISTS categories_is_active_idx ON categories(is_active);
CREATE INDEX IF NOT EXISTS categories_show_on_home_idx ON categories(show_on_home);
CREATE INDEX IF NOT EXISTS categories_sort_order_idx ON categories(sort_order);

CREATE TABLE IF NOT EXISTS places (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  area TEXT NOT NULL DEFAULT 'المنصورية',
  place_type TEXT NOT NULL DEFAULT 'shop' CHECK (place_type IN ('shop', 'person')),
  name_ar TEXT NOT NULL,
  name_en TEXT,
  description_ar TEXT,
  description_en TEXT,
  phone TEXT NOT NULL,
  whatsapp TEXT,
  address_text TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  image_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_note TEXT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS places_provider_idx ON places(provider_id);
CREATE INDEX IF NOT EXISTS places_area_idx ON places(area);
CREATE INDEX IF NOT EXISTS places_status_idx ON places(status);
CREATE INDEX IF NOT EXISTS places_type_idx ON places(place_type);
CREATE INDEX IF NOT EXISTS places_deleted_at_idx ON places(deleted_at);
CREATE INDEX IF NOT EXISTS places_created_at_idx ON places(created_at DESC);
CREATE INDEX IF NOT EXISTS places_updated_idx ON places(updated_at);
CREATE INDEX IF NOT EXISTS places_name_ar_trgm_idx ON places USING gin (name_ar gin_trgm_ops);

CREATE TABLE IF NOT EXISTS place_categories (
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (place_id, category_id)
);

CREATE INDEX IF NOT EXISTS place_categories_category_id_idx ON place_categories(category_id);

CREATE TABLE IF NOT EXISTS place_services (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  name_ar TEXT NOT NULL,
  description_ar TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS place_services_place_id_idx ON place_services(place_id);
CREATE INDEX IF NOT EXISTS place_services_sort_order_idx ON place_services(sort_order);

CREATE TABLE IF NOT EXISTS place_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS place_images_place_idx ON place_images(place_id);

CREATE TABLE IF NOT EXISTS place_edit_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  provider_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS edit_req_place_idx ON place_edit_requests(place_id);
CREATE INDEX IF NOT EXISTS edit_req_provider_idx ON place_edit_requests(provider_id);
CREATE INDEX IF NOT EXISTS edit_req_status_idx ON place_edit_requests(status);

CREATE TABLE IF NOT EXISTS offers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  place_service_id UUID REFERENCES place_services(id) ON DELETE SET NULL,
  title_ar TEXT NOT NULL,
  description_ar TEXT,
  expires_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_note TEXT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS offers_place_id_idx ON offers(place_id);
CREATE INDEX IF NOT EXISTS offers_place_service_id_idx ON offers(place_service_id);
CREATE INDEX IF NOT EXISTS offers_status_idx ON offers(status);
CREATE INDEX IF NOT EXISTS offers_expires_at_idx ON offers(expires_at);
CREATE INDEX IF NOT EXISTS offers_deleted_at_idx ON offers(deleted_at);
CREATE INDEX IF NOT EXISTS offers_created_at_idx ON offers(created_at DESC);
CREATE INDEX IF NOT EXISTS offers_updated_idx ON offers(updated_at);

CREATE TABLE IF NOT EXISTS news (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title_ar TEXT NOT NULL,
  body_ar TEXT,
  image_url TEXT,
  is_pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS news_is_pinned_idx ON news(is_pinned);
CREATE INDEX IF NOT EXISTS news_created_at_idx ON news(created_at DESC);

CREATE TABLE IF NOT EXISTS favorites (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, place_id)
);

CREATE INDEX IF NOT EXISTS favorites_user_id_idx ON favorites(user_id);
CREATE INDEX IF NOT EXISTS favorites_created_at_idx ON favorites(created_at DESC);

CREATE TABLE IF NOT EXISTS likes (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, place_id)
);

CREATE INDEX IF NOT EXISTS likes_place_idx ON likes(place_id);

CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  place_id UUID NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, place_id)
);

CREATE INDEX IF NOT EXISTS reports_place_id_idx ON reports(place_id);
CREATE INDEX IF NOT EXISTS reports_user_id_idx ON reports(user_id);
CREATE INDEX IF NOT EXISTS reports_status_idx ON reports(status);
CREATE INDEX IF NOT EXISTS reports_created_at_idx ON reports(created_at DESC);

CREATE TABLE IF NOT EXISTS device_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT CHECK (platform IN ('android', 'ios', 'web')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, token)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS audit_log_admin_id_idx ON audit_log(admin_id);
CREATE INDEX IF NOT EXISTS audit_log_action_idx ON audit_log(action);
CREATE INDEX IF NOT EXISTS audit_log_target_type_idx ON audit_log(target_type);
CREATE INDEX IF NOT EXISTS audit_log_target_id_idx ON audit_log(target_id);
CREATE INDEX IF NOT EXISTS audit_log_created_at_idx ON audit_log(created_at DESC);

CREATE TABLE IF NOT EXISTS app_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==================== VIEWS ====================

CREATE OR REPLACE VIEW place_likes_count
  WITH (security_invoker = true) AS
SELECT place_id, COUNT(*) AS likes_count
FROM likes
GROUP BY place_id;

-- ==================== RLS ====================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE places ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_edit_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;

-- ==================== PROFILES POLICIES ====================
CREATE POLICY "profiles_select_public" ON profiles
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "profiles_update_own" ON profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = id);

-- ==================== CATEGORIES POLICIES ====================
CREATE POLICY "categories_select_public" ON categories
  FOR SELECT TO anon, authenticated
  USING (is_active = true);

CREATE POLICY "categories_insert_admin" ON categories
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "categories_update_admin" ON categories
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "categories_delete_admin" ON categories
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==================== NEWS POLICIES ====================
CREATE POLICY "news_select_public" ON news
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "news_insert_admin" ON news
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "news_update_admin" ON news
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "news_delete_admin" ON news
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==================== PLACES POLICIES ====================
CREATE POLICY "places_select_public" ON places
  FOR SELECT TO anon, authenticated
  USING (
    status = 'approved'
    AND deleted_at IS NULL
    AND (provider_id IS NULL OR provider_id NOT IN (
      SELECT id FROM profiles WHERE is_banned = TRUE
    ))
  );

CREATE POLICY "places_select_provider_own" ON places
  FOR SELECT TO authenticated
  USING (auth.uid() = provider_id);

CREATE POLICY "places_insert_provider" ON places
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = provider_id);

CREATE POLICY "places_insert_admin" ON places
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Provider can update own places but CANNOT change status
CREATE POLICY "places_update_provider_own" ON places
  FOR UPDATE TO authenticated
  USING (auth.uid() = provider_id)
  WITH CHECK (auth.uid() = provider_id AND status = (SELECT p.status FROM places p WHERE p.id = places.id));

-- Admin can update any place including status changes
CREATE POLICY "places_update_admin" ON places
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==================== PLACE_CATEGORIES POLICIES ====================
CREATE POLICY "place_categories_select_public" ON place_categories
  FOR SELECT TO anon, authenticated
  USING (place_id IN (SELECT id FROM places WHERE status = 'approved' AND deleted_at IS NULL));

CREATE POLICY "place_categories_manage_provider_own" ON place_categories
  FOR ALL TO authenticated
  USING (place_id IN (SELECT id FROM places WHERE provider_id = auth.uid()));

-- ==================== PLACE_SERVICES POLICIES ====================
CREATE POLICY "place_services_select_public" ON place_services
  FOR SELECT TO anon, authenticated
  USING (place_id IN (SELECT id FROM places WHERE status = 'approved' AND deleted_at IS NULL));

CREATE POLICY "place_services_manage_provider_own" ON place_services
  FOR ALL TO authenticated
  USING (place_id IN (SELECT id FROM places WHERE provider_id = auth.uid()));

-- ==================== PLACE_IMAGES POLICIES ====================
CREATE POLICY "place_images_select_public" ON place_images
  FOR SELECT TO anon, authenticated
  USING (place_id IN (SELECT id FROM places WHERE status = 'approved' AND deleted_at IS NULL));

CREATE POLICY "place_images_manage_provider_own" ON place_images
  FOR ALL TO authenticated
  USING (place_id IN (SELECT id FROM places WHERE provider_id = auth.uid()));

-- ==================== PLACE_EDIT_REQUESTS POLICIES ====================
CREATE POLICY "place_edit_requests_select_provider_own" ON place_edit_requests
  FOR SELECT TO authenticated
  USING (place_id IN (SELECT id FROM places WHERE provider_id = auth.uid()));

CREATE POLICY "place_edit_requests_insert_provider" ON place_edit_requests
  FOR INSERT TO authenticated
  WITH CHECK (place_id IN (SELECT id FROM places WHERE provider_id = auth.uid()));

-- Admin can view and manage all edit requests
CREATE POLICY "place_edit_requests_select_admin" ON place_edit_requests
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "place_edit_requests_update_admin" ON place_edit_requests
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==================== OFFERS POLICIES ====================
CREATE POLICY "offers_select_public" ON offers
  FOR SELECT TO anon, authenticated
  USING (status = 'approved' AND deleted_at IS NULL);

-- Provider can manage own offers but CANNOT change status
CREATE POLICY "offers_manage_provider_own" ON offers
  FOR ALL TO authenticated
  USING (place_id IN (SELECT id FROM places WHERE provider_id = auth.uid()))
  WITH CHECK (place_id IN (SELECT id FROM places WHERE provider_id = auth.uid()) AND status = (SELECT o.status FROM offers o WHERE o.id = offers.id));

CREATE POLICY "offers_update_admin" ON offers
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "offers_delete_admin" ON offers
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==================== FAVORITES POLICIES ====================
CREATE POLICY "favorites_manage_own" ON favorites
  FOR ALL TO authenticated
  USING (auth.uid() = user_id);

-- ==================== LIKES POLICIES ====================
CREATE POLICY "likes_select_public" ON likes
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "likes_insert_own" ON likes
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "likes_delete_own" ON likes
  FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ==================== REPORTS POLICIES ====================
CREATE POLICY "reports_insert_own" ON reports
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "reports_select_admin" ON reports
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "reports_update_admin" ON reports
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "reports_delete_admin" ON reports
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==================== DEVICE_TOKENS POLICIES ====================
CREATE POLICY "device_tokens_manage_own" ON device_tokens
  FOR ALL TO authenticated
  USING (auth.uid() = user_id);

-- ==================== AUDIT_LOG POLICIES ====================
CREATE POLICY "audit_log_select_admin" ON audit_log
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "audit_log_insert_admin" ON audit_log
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- ==================== APP_CONFIG POLICIES ====================
CREATE POLICY "app_config_select_public" ON app_config
  FOR SELECT TO anon, authenticated
  USING (true);

-- ==================== FUNCTIONS & TRIGGERS ====================

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, full_name)
  VALUES (new.id, COALESCE(new.raw_user_meta_data->>'full_name', ''));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE handle_new_user();

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_profiles_updated ON profiles;
CREATE TRIGGER trg_profiles_updated BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE PROCEDURE touch_updated_at();
DROP TRIGGER IF EXISTS trg_places_updated ON places;
CREATE TRIGGER trg_places_updated BEFORE UPDATE ON places FOR EACH ROW EXECUTE PROCEDURE touch_updated_at();
DROP TRIGGER IF EXISTS trg_offers_updated ON offers;
CREATE TRIGGER trg_offers_updated BEFORE UPDATE ON offers FOR EACH ROW EXECUTE PROCEDURE touch_updated_at();
DROP TRIGGER IF EXISTS trg_edit_req_updated ON place_edit_requests;
CREATE TRIGGER trg_edit_req_updated BEFORE UPDATE ON place_edit_requests FOR EACH ROW EXECUTE PROCEDURE touch_updated_at();
DROP TRIGGER IF EXISTS trg_reports_updated ON reports;
CREATE TRIGGER trg_reports_updated BEFORE UPDATE ON reports FOR EACH ROW EXECUTE PROCEDURE touch_updated_at();
DROP TRIGGER IF EXISTS trg_categories_updated ON categories;
CREATE TRIGGER trg_categories_updated BEFORE UPDATE ON categories FOR EACH ROW EXECUTE PROCEDURE touch_updated_at();
DROP TRIGGER IF EXISTS trg_news_updated ON news;
CREATE TRIGGER trg_news_updated BEFORE UPDATE ON news FOR EACH ROW EXECUTE PROCEDURE touch_updated_at();

CREATE OR REPLACE FUNCTION check_category_limit()
RETURNS TRIGGER AS $$
DECLARE
  cat_count INT;
  p_type TEXT;
  max_cats INT;
BEGIN
  SELECT place_type INTO p_type FROM places WHERE id = NEW.place_id;
  SELECT COUNT(*) INTO cat_count FROM place_categories WHERE place_id = NEW.place_id;
  max_cats := CASE p_type WHEN 'shop' THEN 1 WHEN 'person' THEN 2 ELSE 1 END;
  IF cat_count >= max_cats THEN
    RAISE EXCEPTION 'تجاوزت الحد المسموح من الكاتيجوريز (%)', max_cats;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_category_limit ON place_categories;
CREATE TRIGGER trg_category_limit BEFORE INSERT ON place_categories FOR EACH ROW EXECUTE PROCEDURE check_category_limit();

CREATE OR REPLACE FUNCTION check_provider_limits()
RETURNS TRIGGER AS $$
DECLARE
  shop_count INT;
  person_count INT;
  max_shops INT;
  max_persons INT;
BEGIN
  SELECT COALESCE(value::INT, 3) INTO max_shops FROM app_config WHERE key = 'max_shop_per_provider';
  SELECT COALESCE(value::INT, 5) INTO max_persons FROM app_config WHERE key = 'max_person_per_provider';
  IF max_shops IS NULL THEN max_shops := 3; END IF;
  IF max_persons IS NULL THEN max_persons := 5; END IF;
  SELECT COUNT(*) INTO shop_count FROM places WHERE provider_id = NEW.provider_id AND place_type = 'shop' AND deleted_at IS NULL;
  SELECT COUNT(*) INTO person_count FROM places WHERE provider_id = NEW.provider_id AND place_type = 'person' AND deleted_at IS NULL;
  IF NEW.place_type = 'shop' AND shop_count >= max_shops THEN
    RAISE EXCEPTION 'مسموح بـ % محل بس حالياً', max_shops;
  END IF;
  IF NEW.place_type = 'person' AND person_count >= max_persons THEN
    RAISE EXCEPTION 'مسموح بـ % profile شخصي بس', max_persons;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_provider_limits ON places;
CREATE TRIGGER trg_provider_limits BEFORE INSERT ON places FOR EACH ROW EXECUTE PROCEDURE check_provider_limits();

-- ==================== SEED CONFIG ====================
INSERT INTO app_config (key, value) VALUES ('max_shop_per_provider', '3') ON CONFLICT (key) DO NOTHING;
INSERT INTO app_config (key, value) VALUES ('max_person_per_provider', '5') ON CONFLICT (key) DO NOTHING;
